package ru.bank.bsp.card.model;

public enum Status {
    ACTIVE, BLOCKED_BY_USER, BLOCKED_BY_BANK, CLOSED, UNKNOWN, NOT_ACTIVE, MONTH_BEFORE_EXPIRE, IN_DEPARTMENT,
    IN_PRODUCTION, ORDERED, DELIVERY_BY_COURIER, DELIVERY_TO_DEPARTMENT
}
