package ru.bank.bsp.finance.model;

public enum CardState {
    ORDERED, IN_PRODUCTION, DELIVERY_BY_COURIER, DELIVERY_TO_DEPARTMENT, IN_DEPARTMENT, NOT_ACTIVE, ACTIVE,
    MONTH_BEFORE_EXPIRE, BLOCKED_BY_BANK, BLOCKED_BY_USER, CLOSED, UNKNOWN
}
