package ru.bank.bsp.statement.model;

public enum Currency {
    AED, AFA, ALL, AMD, ANG, AOA, AON, ARS, ATS, AFN, AUD, AWG, AZM, AZN, BAD, BAM, BBD, BDT, BEF, BGL, BGN, BHD, BIF,
    BMD, BND, BRC, BOB, BRL, BSD, BTN, BWP, BYN, BYR, BZD, CAD, CDF, CHF, CLP, CNH, CNX, CNY, COP, CRC, CSD, CSK, CUP,
    CVE, CYP, CZK, DDM, DEM, DJF, DKK, DOP, DZD, ECS, EEK, EGP, ERN, ESP, ETB, EUR, FIM, FJD, FKP, FRF, GBP, GEL, GEK,
    GHC, GHS, GIP, GMD, GNF, GRD, GTQ, GWP, GYD, GQE, HKD, HNL, HRK, HTG, HUF, IDR, IEP, ILS, INR, IQD, IRA, IRR, ITL,
    ISK, JMD, JOD, JPY, KES, KGS, KHR, KMF, KPW, KRW, KWD, KYD, KZT, LAK, LBP, LKR, LRD, LSL, LTL, LUF, LVL, LYD, MAD,
    MDL, MGA, MGF, MKD, MMK, MNT, MLF, MOP, MRO, MTL, MUR, MVR, MWK, MXN, MYR, MZM, MZN, NAD, NGN, NIO, NLG, NOK, NPR,
    NZD, OMR, PAB, PEN, PGK, PHP, PKR, PLN, PLZ, PTE, PTL, PTS, PYG, QAR, ROL, RON, RSD, RUB, RUR, RWF, SAR, SBD, SCR,
    SDA, SDD, SDG, SEK, SGD, SHP, SIT, SLL, SKK, SOS, SRD, SRG, SSP, STD, SVC, SYP, SZL, THB, TJR, TJS, TLP, TMM, TMT,
    TND, TOP, TPE, TRL, TRY, TTD, TWD, TZS, UAK, UNK, UAH, UGX, USD, UYU, UZS, VEB, VEF, VND, VUV, WST, XAF, XCD, XEU,
    XOF, XPF, YDD, YER, YUD, YYY, ZAR, ZMK, ZMW, ZRN, ZWD
}
