package ru.bank.bsp.statement.model;

public enum StatementType {
    EMBASSY,
    ACCOUNT_LACK,
    GUARANTOR_STATUS,
    ALL_LOAN_INFO,
    UNUSE_MATERNAL_CAPITAL,
    MORTGAGE_REPAYMENT_CHARACTER,
    MORTGAGE_DEPT,
    SUBSEQUENT_BAIL,
    FOR_MATERNAL_CAPITAL,
    INTEREST_PAID_MORTGAGE,
    DEPOSIT_STATUS,
    CIVIL_SERVANTS,
    CURRENT_DEBT,
    CLOSING_LOAN,
    ABSENCE_LOANS,
    ACCOUNT_STATEMENT,
    PAYSLIP,
    ACCOUNT_DETAILS,
    CARD_STATEMENT,
    LEGAL_ACCOUNT_STATEMENT
}
